name: Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build-and-test-frontend:
        name: Build and test Vue FE
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '22'
            -   name: Cache node modules
                uses: actions/cache@v3
                with:
                    path: ~/fe/node_modules
                    key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            -   name: Install dependencies
                run: |
                    cd fe
                    yarn install
            -   name: Run Eslint
                run: |
                    cd fe
                    yarn eslint --max-warnings 0
            -   name: Run Prettier
                run: |
                    cd fe
                    yarn prettier

    build-and-test-backend:
        name: Build and test Rust BE
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Machete dependency check
                uses: bnjbvr/cargo-machete@main
            -   name: Set up Rust
                uses: actions-rust-lang/setup-rust-toolchain@v1
                with:
                    toolchain: nightly
                    components: clippy
            -   name: Cache cargo registry
                uses: actions/cache@v3
                with:
                    path: ~/.cargo/registry
                    key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
            -   name: Cache cargo build
                uses: actions/cache@v3
                with:
                    path: target
                    key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
            -   name: Build
                run: cargo build --verbose
            -   name: Run clippy
                run: cargo clippy -- -D clippy::all -D warnings -D clippy::pedantic -D clippy::nursery
            -   name: Run tests
                run: cargo test
